// Mocks generated by Mockito 5.4.6 from annotations
// in settings/test/presentation/settings/settings_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/core.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:package_info_plus/package_info_plus.dart' as _i2;
import 'package:settings/data/models/sync/available_language.dart' as _i7;
import 'package:settings/domain/usecases/get_available_languages_usecase.dart'
    as _i6;
import 'package:settings/domain/usecases/get_dynamic_localization_usecase.dart'
    as _i8;
import 'package:settings/domain/usecases/update_user_language_usecase.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePackageInfo_0 extends _i1.SmartFake implements _i2.PackageInfo {
  _FakePackageInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppInfoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppInfoService extends _i1.Mock implements _i3.AppInfoService {
  MockAppInfoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PackageInfo> getPackageInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getPackageInfo, []),
            returnValue: _i4.Future<_i2.PackageInfo>.value(
              _FakePackageInfo_0(this, Invocation.method(#getPackageInfo, [])),
            ),
          )
          as _i4.Future<_i2.PackageInfo>);
}

/// A class which mocks [UpdateUserLanguageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserLanguageUseCase extends _i1.Mock
    implements _i5.UpdateUserLanguageUseCase {
  MockUpdateUserLanguageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.Either<_i3.Failure, void>> call(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#call, [languageCode]),
            returnValue: _i4.Future<_i3.Either<_i3.Failure, void>>.value(
              _FakeEither_1<_i3.Failure, void>(
                this,
                Invocation.method(#call, [languageCode]),
              ),
            ),
          )
          as _i4.Future<_i3.Either<_i3.Failure, void>>);
}

/// A class which mocks [GetAvailableLanguagesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAvailableLanguagesUseCase extends _i1.Mock
    implements _i6.GetAvailableLanguagesUseCase {
  MockGetAvailableLanguagesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.Either<_i3.Failure, List<_i7.AvailableLanguage>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i3.Either<_i3.Failure, List<_i7.AvailableLanguage>>
                >.value(
                  _FakeEither_1<_i3.Failure, List<_i7.AvailableLanguage>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i3.Either<_i3.Failure, List<_i7.AvailableLanguage>>>);
}

/// A class which mocks [GetDynamicLocalizationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDynamicLocalizationUseCase extends _i1.Mock
    implements _i8.GetDynamicLocalizationUseCase {
  MockGetDynamicLocalizationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.Either<_i3.Failure, void>> call(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#call, [languageCode]),
            returnValue: _i4.Future<_i3.Either<_i3.Failure, void>>.value(
              _FakeEither_1<_i3.Failure, void>(
                this,
                Invocation.method(#call, [languageCode]),
              ),
            ),
          )
          as _i4.Future<_i3.Either<_i3.Failure, void>>);
}
