// Mocks generated by Mockito 5.4.6 from annotations
// in trends/test/data/datasources/trends_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:talker/talker.dart' as _i4;
import 'package:trends/data/datasources/remote/trends_client.dart' as _i5;
import 'package:trends/data/models/coin_market_model.dart' as _i3;
import 'package:trends/data/models/coin_market_ohlcv_model.dart' as _i7;
import 'package:trends/data/models/coin_market_response.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCoinMarketResponse_0 extends _i1.SmartFake implements _i2.CoinMarketResponse {
  _FakeCoinMarketResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCoinMarketModel_1 extends _i1.SmartFake implements _i3.CoinMarketModel {
  _FakeCoinMarketModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTalkerSettings_2 extends _i1.SmartFake implements _i4.TalkerSettings {
  _FakeTalkerSettings_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TrendsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrendsClient extends _i1.Mock implements _i5.TrendsClient {
  MockTrendsClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.CoinMarketResponse> getCoinMarkets({
    int? start = 1,
    int? limit = 20,
    String? convert,
    String? sort,
    String? sortDir,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCoinMarkets, [], {
              #start: start,
              #limit: limit,
              #convert: convert,
              #sort: sort,
              #sortDir: sortDir,
            }),
            returnValue: _i6.Future<_i2.CoinMarketResponse>.value(
              _FakeCoinMarketResponse_0(
                this,
                Invocation.method(#getCoinMarkets, [], {
                  #start: start,
                  #limit: limit,
                  #convert: convert,
                  #sort: sort,
                  #sortDir: sortDir,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.CoinMarketResponse>);

  @override
  _i6.Future<Map<String, _i3.CoinMarketModel>> getCoinInfo({required String? symbol}) =>
      (super.noSuchMethod(
            Invocation.method(#getCoinInfo, [], {#symbol: symbol}),
            returnValue: _i6.Future<Map<String, _i3.CoinMarketModel>>.value(
              <String, _i3.CoinMarketModel>{},
            ),
          )
          as _i6.Future<Map<String, _i3.CoinMarketModel>>);

  @override
  _i6.Future<_i3.CoinMarketModel> getCoinPriceConversion({
    required String? symbol,
    required double? amount,
    String? convert,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCoinPriceConversion, [], {
              #symbol: symbol,
              #amount: amount,
              #convert: convert,
            }),
            returnValue: _i6.Future<_i3.CoinMarketModel>.value(
              _FakeCoinMarketModel_1(
                this,
                Invocation.method(#getCoinPriceConversion, [], {
                  #symbol: symbol,
                  #amount: amount,
                  #convert: convert,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.CoinMarketModel>);

  @override
  _i6.Future<List<_i3.CoinMarketModel>> getGlobalMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalMetrics, []),
            returnValue: _i6.Future<List<_i3.CoinMarketModel>>.value(<_i3.CoinMarketModel>[]),
          )
          as _i6.Future<List<_i3.CoinMarketModel>>);

  @override
  _i6.Future<List<_i3.CoinMarketModel>> getMaps() =>
      (super.noSuchMethod(
            Invocation.method(#getMaps, []),
            returnValue: _i6.Future<List<_i3.CoinMarketModel>>.value(<_i3.CoinMarketModel>[]),
          )
          as _i6.Future<List<_i3.CoinMarketModel>>);

  @override
  _i6.Future<Map<String, _i7.CoinMarketOhlcvModel>> getOhlcv({
    required String? symbol,
    required String? interval,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOhlcv, [], {#symbol: symbol, #interval: interval}),
            returnValue: _i6.Future<Map<String, _i7.CoinMarketOhlcvModel>>.value(
              <String, _i7.CoinMarketOhlcvModel>{},
            ),
          )
          as _i6.Future<Map<String, _i7.CoinMarketOhlcvModel>>);
}

/// A class which mocks [Talker].
///
/// See the documentation for Mockito's code generation for more information.
class MockTalker extends _i1.Mock implements _i4.Talker {
  MockTalker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TalkerSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeTalkerSettings_2(this, Invocation.getter(#settings)),
          )
          as _i4.TalkerSettings);

  @override
  _i6.Stream<_i4.TalkerData> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.TalkerData>.empty(),
          )
          as _i6.Stream<_i4.TalkerData>);

  @override
  List<_i4.TalkerData> get history =>
      (super.noSuchMethod(Invocation.getter(#history), returnValue: <_i4.TalkerData>[])
          as List<_i4.TalkerData>);

  @override
  set settings(_i4.TalkerSettings? value) =>
      super.noSuchMethod(Invocation.setter(#settings, value), returnValueForMissingStub: null);

  @override
  void configure({
    _i4.TalkerLogger? logger,
    _i4.TalkerSettings? settings,
    _i4.TalkerObserver? observer,
    filter,
    _i4.TalkerErrorHandler? errorHandler,
    _i4.TalkerHistory? history,
  }) =>
      throw UnsupportedError(r'"configure" cannot be used without a mockito fallback generator.');

  @override
  void handle(Object? exception, [StackTrace? stackTrace, dynamic msg]) => super.noSuchMethod(
    Invocation.method(#handle, [exception, stackTrace, msg]),
    returnValueForMissingStub: null,
  );

  @override
  void log(
    dynamic message, {
    _i4.LogLevel? logLevel = _i4.LogLevel.debug,
    Object? exception,
    StackTrace? stackTrace,
    _i4.AnsiPen? pen,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [message],
      {#logLevel: logLevel, #exception: exception, #stackTrace: stackTrace, #pen: pen},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void logTyped(_i4.TalkerLog? log) =>
      super.noSuchMethod(Invocation.method(#logTyped, [log]), returnValueForMissingStub: null);

  @override
  void logCustom(_i4.TalkerLog? log) =>
      super.noSuchMethod(Invocation.method(#logCustom, [log]), returnValueForMissingStub: null);

  @override
  void critical(dynamic msg, [Object? exception, StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#critical, [msg, exception, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void debug(dynamic msg, [Object? exception, StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#debug, [msg, exception, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void error(dynamic msg, [Object? exception, StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#error, [msg, exception, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void info(dynamic msg, [Object? exception, StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#info, [msg, exception, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void verbose(dynamic msg, [Object? exception, StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#verbose, [msg, exception, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void warning(dynamic msg, [Object? exception, StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#warning, [msg, exception, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void cleanHistory() =>
      super.noSuchMethod(Invocation.method(#cleanHistory, []), returnValueForMissingStub: null);

  @override
  void enable() =>
      super.noSuchMethod(Invocation.method(#enable, []), returnValueForMissingStub: null);

  @override
  void disable() =>
      super.noSuchMethod(Invocation.method(#disable, []), returnValueForMissingStub: null);
}
