// Mocks generated by Mockito 5.4.6 from annotations
// in trends/test/domain/usecases/get_coin_markets_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trends/domain/entities/coin_market_entity.dart' as _i5;
import 'package:trends/domain/entities/coin_market_ohlcv_entity.dart' as _i6;
import 'package:trends/domain/repositories/trends_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [TrendsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrendsRepository extends _i1.Mock implements _i3.TrendsRepository {
  MockTrendsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i2.Failure, List<_i5.CoinMarketEntity>>> getCoinMarkets({
    int? page = 1,
    int? limit = 20,
    String? convert,
    String? sort,
    String? sortDir,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCoinMarkets, [], {
              #page: page,
              #limit: limit,
              #convert: convert,
              #sort: sort,
              #sortDir: sortDir,
            }),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, List<_i5.CoinMarketEntity>>>.value(
              _FakeEither_0<_i2.Failure, List<_i5.CoinMarketEntity>>(
                this,
                Invocation.method(#getCoinMarkets, [], {
                  #page: page,
                  #limit: limit,
                  #convert: convert,
                  #sort: sort,
                  #sortDir: sortDir,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, List<_i5.CoinMarketEntity>>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, Map<String, _i5.CoinMarketEntity>>> getCoinInfo({
    required String? symbol,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCoinInfo, [], {#symbol: symbol}),
            returnValue:
                _i4.Future<_i2.Either<_i2.Failure, Map<String, _i5.CoinMarketEntity>>>.value(
                  _FakeEither_0<_i2.Failure, Map<String, _i5.CoinMarketEntity>>(
                    this,
                    Invocation.method(#getCoinInfo, [], {#symbol: symbol}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, Map<String, _i5.CoinMarketEntity>>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, _i5.CoinMarketEntity>> getCoinPriceConversion({
    required String? symbol,
    required double? amount,
    String? convert,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCoinPriceConversion, [], {
              #symbol: symbol,
              #amount: amount,
              #convert: convert,
            }),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, _i5.CoinMarketEntity>>.value(
              _FakeEither_0<_i2.Failure, _i5.CoinMarketEntity>(
                this,
                Invocation.method(#getCoinPriceConversion, [], {
                  #symbol: symbol,
                  #amount: amount,
                  #convert: convert,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, _i5.CoinMarketEntity>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, List<_i5.CoinMarketEntity>>> getGlobalMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalMetrics, []),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, List<_i5.CoinMarketEntity>>>.value(
              _FakeEither_0<_i2.Failure, List<_i5.CoinMarketEntity>>(
                this,
                Invocation.method(#getGlobalMetrics, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, List<_i5.CoinMarketEntity>>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, List<_i5.CoinMarketEntity>>> getMaps() =>
      (super.noSuchMethod(
            Invocation.method(#getMaps, []),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, List<_i5.CoinMarketEntity>>>.value(
              _FakeEither_0<_i2.Failure, List<_i5.CoinMarketEntity>>(
                this,
                Invocation.method(#getMaps, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, List<_i5.CoinMarketEntity>>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, Map<String, _i6.CoinMarketOhlcvEntity>>> getOhlcv({
    required String? symbol,
    required String? interval,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOhlcv, [], {#symbol: symbol, #interval: interval}),
            returnValue:
                _i4.Future<_i2.Either<_i2.Failure, Map<String, _i6.CoinMarketOhlcvEntity>>>.value(
                  _FakeEither_0<_i2.Failure, Map<String, _i6.CoinMarketOhlcvEntity>>(
                    this,
                    Invocation.method(#getOhlcv, [], {#symbol: symbol, #interval: interval}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, Map<String, _i6.CoinMarketOhlcvEntity>>>);
}
