// swift-tools-version: 5.9
// Copyright (c) 2026, one of DanhDue ExOICTIF projects. All rights reserved.

// coverage:ignore-file

import PackageDescription

// {{name.pascalCase()}} — Flutter native plugin, iOS side (Swift Package Manager only).
//
// This plugin has no `.podspec`: FactoryKit 3.x (the DI library) is SPM-only, and the
// Super App template's host has SPM enabled. A plugin generated by `pac_native_plugin`
// therefore needs an SPM-enabled host (Flutter >= 3.44). See the package README.
//
// Package & target: `{{name.snakeCase()}}` (snake_case). Library product:
// `{{name.paramCase()}}` (Flutter's SPM rule — hyphens in the product name only).
// SwiftPM globs `Sources/{{name.snakeCase()}}/**`, so the same manifest serves both
// `has_ui` modes — the brick's `post_gen` hook deletes the unused folders.
let package = Package(
    name: "{{name.snakeCase()}}",
    platforms: [.iOS("15.0")],
    products: [
        .library(name: "{{name.paramCase()}}", targets: ["{{name.snakeCase()}}"])
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
        .package(url: "https://github.com/hmlongco/Factory.git", exact: "3.3.2")
    ],
    targets: [
        .target(
            name: "{{name.snakeCase()}}",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                .product(name: "FactoryKit", package: "Factory")
            ]
        ),
        .testTarget(
            name: "{{name.snakeCase()}}Tests",
            dependencies: ["{{name.snakeCase()}}"]
        )
    ]
)
