// Copyright (c) 2026, one of DanhDue ExOICTIF projects. All rights reserved.

// coverage:ignore-file

// Autogenerated from Pigeon. Do not edit directly.

import Foundation
import Flutter

protocol {{name.pascalCase()}}HostApi {
    func getPlatformVersion() throws -> String
}

class {{name.pascalCase()}}HostApiSetup {
    static func setUp(binaryMessenger: FlutterBinaryMessenger, api: {{name.pascalCase()}}HostApi?) {
        let channel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.{{name.snakeCase()}}.{{name.pascalCase()}}HostApi.getPlatformVersion",
            binaryMessenger: binaryMessenger,
            codec: FlutterStandardMessageCodec.sharedInstance()
        )
        if let api = api {
            channel.setMessageHandler { _, reply in
                do {
                    let result = try api.getPlatformVersion()
                    reply([result])
                } catch {
                    reply([nil, error.localizedDescription])
                }
            }
        } else {
            channel.setMessageHandler(nil)
        }
    }
}
