// Copyright (c) 2026, one of DanhDue ExOICTIF projects. All rights reserved.

import 'package:bloc_digital_wallet/core/network/app_uri.dart';
import 'package:dio/dio.dart';
import '../../../../features/authentication/data/datasources/local/auth_local_datasource.dart';
import '../../../../features/authentication/data/datasources/remote/auth_client.dart';
import 'package:talker_flutter/talker_flutter.dart';

import '../../../../core/services/auth_stream_service.dart';

class AuthInterceptor extends QueuedInterceptor {
  final Dio _dio;
  final AuthLocalDataSource _localDataSource;
  final AuthClient _authClient;
  final Talker _talker;
  final AuthStreamService _authStreamService;

  AuthInterceptor(
    this._dio,
    this._localDataSource,
    this._authClient,
    this._talker,
    this._authStreamService,
  );

  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) async {
    final path = options.path;
    final isAuthRequest =
        path.contains('/${AppUri.login}') || path.contains('/${AppUri.register}');

    if (!isAuthRequest) {
      final token = await _localDataSource.getAccessToken();
      if (token != null && token.isNotEmpty) {
        options.headers['Authorization'] = 'Bearer $token';
      }
    }
    super.onRequest(options, handler);
  }

  @override
  void onError(DioException err, ErrorInterceptorHandler handler) async {
    if (err.response?.statusCode == 401) {
      // ISSUE: Infinite Loop Risk
      // If a request fails with 401, we try to refresh the token and retry.
      // If the *retried* request ALSO fails with 401 (e.g., the new token was immediately revoked),
      // different logic is needed to prevent recursively triggering this 401 handler forever.
      // SOLUTION: Check for 'is_retry' flag in request options.
      if (err.requestOptions.extra.containsKey('is_retry')) {
        _talker.warning(
          'AuthInterceptor: Retried request failed with 401. Propagating error to avoid infinite loop.',
        );
        // ISSUE: Persistent Authorization Failure
        // Even after a supposed refresh (or if this was just a second attempt), the server rejected us.
        // SOLUTION: The session is fundamentally broken. The error will propagate to the UI/Bloc, which should trigger a LOGOUT.
        _authStreamService.logout();
        return handler.next(err);
      }

      _talker.warning('AuthInterceptor: 401 Detected. Attempting refresh...');

      final requestToken = err.requestOptions.headers['Authorization']?.toString().replaceAll(
        'Bearer ',
        '',
      );
      final currentToken = await _localDataSource.getAccessToken();

      // ISSUE: Race Conditions / Staleness
      // Multiple requests might fail with 401 simultaneously.
      // If Request A triggers a refresh, tokens change.
      // When Request B (which failed with the OLD token) hits this interceptor, if we blindly refresh again,
      // we might invalidate the valid token generated by Request A.
      // SOLUTION: Check if the token in the failed request matches the current storage token.
      // If they differ, it means a refresh likely already happened. Retry immediately with the current valid token.
      if (requestToken != null && currentToken != null && requestToken != currentToken) {
        _talker.info(
          'AuthInterceptor: Token was stale (refresh likely happened). Retrying with current token.',
        );
        return _retry(err.requestOptions, currentToken, handler);
      }

      final refreshToken = await _localDataSource.getRefreshToken();
      if (refreshToken != null) {
        try {
          // Perform refresh
          // Note: This call uses a separate Dio instance (provided via DI) to avoid circular dependency
          // and ensuring this request itself isn't intercepted by AuthInterceptor.
          final newAuthData = await _authClient.refreshToken(refresh: refreshToken);

          final newAccess = newAuthData.access;
          final newRefresh = newAuthData.refresh;

          if (newAccess != null && newRefresh != null) {
            await _localDataSource.saveTokens(accessToken: newAccess, refreshToken: newRefresh);
            _talker.info(
              'AuthInterceptor: Token refreshed successfully. Retrying original request.',
            );
            return _retry(err.requestOptions, newAccess, handler);
          }
        } catch (e) {
          // ISSUE: Refresh Failed / Session Expired
          // The refresh token itself is expired, revoked, or invalid (401/403 from refresh endpoint).
          // SOLUTION: The User Session is completely DEAD. We MUST LOGOUT.
          // 1. Clear local tokens.
          // 2. Propagate error or trigger global logout event (e.g. via Stream or Router).
          _talker.error('AuthInterceptor: Refresh failed. Clearing tokens (Logout Trigger).', e);
          await _localDataSource.clearTokens();
          _authStreamService.logout();
        }
      } else {
        // ISSUE: No Refresh Token
        // We received a 401 but have no refresh token to recover with.
        // SOLUTION: We cannot recover. Propagate error to trigger LOGOUT.
        _talker.warning('AuthInterceptor: No refresh token found. Triggering logout.');
        await _localDataSource.clearTokens();
        _authStreamService.logout();
      }
    }
    super.onError(err, handler);
  }

  Future<void> _retry(
    RequestOptions requestOptions,
    String newToken,
    ErrorInterceptorHandler handler,
  ) async {
    final options = Options(
      method: requestOptions.method,
      headers: {...requestOptions.headers, 'Authorization': 'Bearer $newToken'},
      // Mark this request as a retry to prevent infinite loops if it fails again
      extra: {...requestOptions.extra, 'is_retry': true},
    );

    try {
      final response = await _dio.request<dynamic>(
        requestOptions.path,
        data: requestOptions.data,
        queryParameters: requestOptions.queryParameters,
        options: options,
      );
      handler.resolve(response);
    } on DioException catch (e) {
      handler.next(e);
    }
  }
}
