// Copyright (c) 2026, one of DanhDue ExOICTIF projects. All rights reserved.

// coverage:ignore-file
// Autogenerated from Pigeon. Do not edit directly.

import Flutter
import Foundation

public struct Pigeon{{name.pascalCase()}}Data: Sendable {
    public var id: String
    public var title: String
    public var timestamp: Int64

    public init(id: String, title: String, timestamp: Int64 = 0) {
        self.id = id
        self.title = title
        self.timestamp = timestamp
    }

    static func fromList(_ list: [Any?]) -> Pigeon{{name.pascalCase()}}Data? {
        guard let id = list[0] as? String,
              let title = list[1] as? String
        else {
            return nil
        }
        let timestamp = (list[2] as? NSNumber)?.int64Value ?? 0
        return Pigeon{{name.pascalCase()}}Data(id: id, title: title, timestamp: timestamp)
    }

    func toList() -> [Any?] {
        [id, title, timestamp]
    }
}

public protocol {{name.pascalCase()}}HostApi {
    func getPlatformVersion() throws -> String
    func getData(completion: @escaping @Sendable (Result<Pigeon{{name.pascalCase()}}Data, Error>) -> Void)
}

public enum {{name.pascalCase()}}HostApiSetup {
    public static var codec: FlutterStandardMessageCodec {
        FlutterStandardMessageCodec.sharedInstance()
    }

    public static func setUp(binaryMessenger: FlutterBinaryMessenger, api: {{name.pascalCase()}}HostApi?) {
        let versionChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.{{name.snakeCase()}}.{{name.pascalCase()}}HostApi.getPlatformVersion",
            binaryMessenger: binaryMessenger,
            codec: codec
        )
        if let api {
            versionChannel.setMessageHandler { _, reply in
                do {
                    let result = try api.getPlatformVersion()
                    reply([result])
                } catch {
                    reply([nil, error.localizedDescription])
                }
            }
        } else {
            versionChannel.setMessageHandler(nil)
        }

        let dataChannel = FlutterBasicMessageChannel(
            name: "dev.flutter.pigeon.{{name.snakeCase()}}.{{name.pascalCase()}}HostApi.getData",
            binaryMessenger: binaryMessenger,
            codec: codec
        )
        if let api {
            dataChannel.setMessageHandler { _, reply in
                api.getData { result in
                    switch result {
                    case let .success(res):
                        reply([res.toList()])
                    case let .failure(error):
                        reply([nil, error.localizedDescription])
                    }
                }
            }
        } else {
            dataChannel.setMessageHandler(nil)
        }
    }
}
