// Mocks generated by Mockito 5.4.6 from annotations
// in settings/test/domain/usecases/get_settings_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:settings/data/models/sync/available_language.dart' as _i9;
import 'package:settings/data/models/sync/sync_bootstrap_request.dart' as _i7;
import 'package:settings/data/models/sync/sync_bootstrap_response.dart' as _i6;
import 'package:settings/data/models/sync/translation_override_response.dart'
    as _i8;
import 'package:settings/domain/entities/settings_entity.dart' as _i5;
import 'package:settings/domain/repositories/settings_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i3.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i2.Failure, _i5.SettingsEntity>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue:
                _i4.Future<_i2.Either<_i2.Failure, _i5.SettingsEntity>>.value(
                  _FakeEither_0<_i2.Failure, _i5.SettingsEntity>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, _i5.SettingsEntity>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, _i6.SyncBootstrapResponse>> bootstrap(
    _i7.SyncBootstrapRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bootstrap, [request]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i2.Failure, _i6.SyncBootstrapResponse>
                >.value(
                  _FakeEither_0<_i2.Failure, _i6.SyncBootstrapResponse>(
                    this,
                    Invocation.method(#bootstrap, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, _i6.SyncBootstrapResponse>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, _i8.TranslationOverrideData>>
  getLocalizationOverrides(
    String? languageCode, {
    String? sinceVersion,
    String? eTag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLocalizationOverrides,
              [languageCode],
              {#sinceVersion: sinceVersion, #eTag: eTag},
            ),
            returnValue:
                _i4.Future<
                  _i2.Either<_i2.Failure, _i8.TranslationOverrideData>
                >.value(
                  _FakeEither_0<_i2.Failure, _i8.TranslationOverrideData>(
                    this,
                    Invocation.method(
                      #getLocalizationOverrides,
                      [languageCode],
                      {#sinceVersion: sinceVersion, #eTag: eTag},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, _i8.TranslationOverrideData>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, String?>> getCachedTranslationVersion(
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTranslationVersion, [languageCode]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, String?>>.value(
              _FakeEither_0<_i2.Failure, String?>(
                this,
                Invocation.method(#getCachedTranslationVersion, [languageCode]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, String?>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> saveCachedTranslationVersion(
    String? languageCode,
    String? version,
    String? checksum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCachedTranslationVersion, [
              languageCode,
              version,
              checksum,
            ]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#saveCachedTranslationVersion, [
                  languageCode,
                  version,
                  checksum,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, Map<String, dynamic>?>>
  getCachedTranslationJson(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTranslationJson, [languageCode]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i2.Failure, Map<String, dynamic>?>
                >.value(
                  _FakeEither_0<_i2.Failure, Map<String, dynamic>?>(
                    this,
                    Invocation.method(#getCachedTranslationJson, [
                      languageCode,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, Map<String, dynamic>?>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> saveCachedTranslationJson(
    String? languageCode,
    Map<String, dynamic>? json,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveCachedTranslationJson, [languageCode, json]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#saveCachedTranslationJson, [
                  languageCode,
                  json,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> deleteCachedTranslation(
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCachedTranslation, [languageCode]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#deleteCachedTranslation, [languageCode]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, List<String>>>
  getAllCachedLanguageCodes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCachedLanguageCodes, []),
            returnValue:
                _i4.Future<_i2.Either<_i2.Failure, List<String>>>.value(
                  _FakeEither_0<_i2.Failure, List<String>>(
                    this,
                    Invocation.method(#getAllCachedLanguageCodes, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, void>> saveAvailableLanguages(
    List<_i9.AvailableLanguage>? languages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveAvailableLanguages, [languages]),
            returnValue: _i4.Future<_i2.Either<_i2.Failure, void>>.value(
              _FakeEither_0<_i2.Failure, void>(
                this,
                Invocation.method(#saveAvailableLanguages, [languages]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, List<_i9.AvailableLanguage>>>
  getAvailableLanguages() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableLanguages, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i2.Failure, List<_i9.AvailableLanguage>>
                >.value(
                  _FakeEither_0<_i2.Failure, List<_i9.AvailableLanguage>>(
                    this,
                    Invocation.method(#getAvailableLanguages, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, List<_i9.AvailableLanguage>>>);

  @override
  _i4.Future<_i2.Either<_i2.Failure, Map<String, dynamic>>> loadBundledFallback(
    String? languageCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadBundledFallback, [languageCode]),
            returnValue:
                _i4.Future<_i2.Either<_i2.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i2.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#loadBundledFallback, [languageCode]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i2.Failure, Map<String, dynamic>>>);
}
